[package]
  edition = "2024"
  name    = "jiraffe"
  version = "0.1.0"

[dependencies]
  anyhow     = "1"
  serde      = { version = "1", features = ["derive"] }
  serde_json = "1"
  thiserror  = "2"

[dev-dependencies]
  tempfile = "3"
