[package]
  edition = "2024"
  name    = "jiraffe"
  version = "0.1.0"

[dependencies]
  anyhow      = "1"
  clearscreen = "4"
  ellipse     = "0.2"
  itertools   = "0.14"
  serde       = { version = "1", features = ["derive"] }
  serde_json  = "1"

[dev-dependencies]
  tempfile = "3"
