# Minimum Supported Rust Version (conservative for tooling)
msrv = "1.84"
# Complexity thresholds
cognitive-complexity-threshold = 20
too-many-arguments-threshold   = 6
type-complexity-threshold      = 150
# API stability (important for JS interop)
avoid-breaking-exported-api = true
# WASM-specific considerations
missing-docs-in-crate-items = false
# Additional lints useful
disallowed-methods = [
] # Add methods you want to avoid
# Size thresholds
pass-by-value-size-limit = 256
trivial-copy-size-limit  = 64
# Other useful settings
max-fn-params-bools                 = 3
max-trait-bounds                    = 3
single-char-binding-names-threshold = 4
